Что такое обёртка над АПИ?
==========================
Источник: https://rapidapi.com/blog/api-glossary/api-wrapper/

В области технологий и разработки программного обеспечения <<api,API>> -- это средства и протоколы, позволяющие получать данные из веб-служб или приложений. Как разработчик, вы всегда ищете, какой-бы полезный API добавить в свой стек. И когда вы найдёте что-то интересное, у вас всегда будет искушение попробовать его. Однако API бывают разных размеров и форм. Некоторые из них очень просты в использовании, но есть также чрезмерно сложные API, которые заставят вас почесать затылок. Если вам нужно использовать широкий спектр связанных API, необходим более изысканный способ упростить чрезмерно сложные API. Тогда на помощь приходят обёртки над API.

== Что такое обёртка над API?

В технологии обёртка -- это любая структура или сущность, которая используется для маскировки или обертывания другого элемента. Он служит двум целям при использовании в программировании. Во-первых, это поможет вам конвертировать данные в совместимый формат. Во-вторых, это помогает упростить сложную сущность или позволяет программе легко выполнять сложные задачи, используя то, что называется абстракцией.

В данном контексте обёртка над API -- это языковой пакет или набор, который инкапсулирует несколько вызовов API, чтобы упростить использование сложных функций. Это помогает разработчикам вызывать различные API-интерфейсы без необходимости их взаимодействия в режиме реального времени. Таким образом, обёртки можно использовать для автоматизации процессов, зависящих от API. Поскольку API позволяют пользователям получать доступ к набору определённых стандартных функций, обёртки над API могут помочь интегрировать несколько вызовов API в одну службу.

Например, допустим, вы хотите найти определённый субреддит в Reddit, но приложение или программа, которую вы создаёте, хочет получить доступ к целевым наборам в конкретных субреддитах. Вместо того, чтобы вызывать API три раза, вы можете вызвать функцию-оболочку, которая объединит все три вызова API в одну задачу. В то время как API потребует, чтобы вы выполняли отдельные вызовы для каждой функции Reddit, обертывание API упрощает процесс, позволяя вам выполнять все вызовы одновременно с одной функцией.

== Что делает обёртка над API?

В двух словах, обёртка над API объединяет несколько вызовов для доступа к определенным стандартным функциям. Он также может быть использован для создания приложений или программ для выполнения более сложных задач в менее удобном формате.

Кроме того, программисты могут использовать обёртки над API для создания точных элементов управления, которых в API часто недостаёт. Например, при работе с приложением или программой, которые позволяют вам вводить некоторые тексты в поле, в большинстве случаев используемые вами API могут разрешать некоторые запрещённые текстовые символы, которые не нужны. Это заставляет вас постоянно получать сообщение об ошибке при попытке вызвать API больше раз, чем рассчитано. Однако обёртка над API проверяет введённые вами тексты перед вызовом API. Например, если ваше приложение не позволяет использовать знак процента, API может позволить вам ввести его в текстовое поле и совершать повторные вызовы до тех пор, пока вы не поймёте свою ошибку. Но при обертывании API ваш текст будет проверен, и все недопустимые символы, такие как знак процента, будут удалены до того, как вы сделаете какие-либо вызовы.

== Как использовать обёртку над API?

В большинстве случаев вы можете использовать обёртки над API, чтобы охватить несколько API, которые помогут вам объединить различные вызовы, что позволит получить доступ к набору связанных функций, а не создавать несколько запросов HTTP API с нуля.

Вы также можете использовать обертывание, чтобы попытаться вернуть данные в знакомой структуре данных, отличной от той, которая предлагается языком. Это расширит идиоматические способы доступа к таким данным и манипулирования ими.

При обертывании API вам не нужно извлекать какую-либо информацию из API при выполнении вызова. Конкретные функции, к которым можно получить доступ через данный API, инкапсулируются в один пакет.

include::glossary.adoc[]
