Синтез операционных и управляющих автоматов
===========================================
Баркалов А.А., Титаренко Л.А.
Донецк, ДонНТУ, 2009

== Введение

Последние шестьдесят лет отмечены быстрым развитием компьютерных наук cite:[barkalov]. Ключевые особенности промышленности в данной области на сегодняшний день следующие:

. Разработка сверхсложных сверхбольших интегральных схем, таких, как программируемые чипы <<sopc,(ПЛИС)>>, где около млрд логических <<ge,вентилей>>. Современная микроэлектроника становится, если не наноэлектроникой, то где-то в этом роде, учитывая уменьшающиеся размеры как транзисторов так и проводников.
. Разработка языков описания аппаратуры <<hdl,(ЯОП)>>, таких как VHDL и Verilog, позволяющих охватить чрезвычайно сложные проекты.
. Повсеместное применение систем автоматизированного проектирования <<cad,(САПР)>> для создания сложных проектов за приемлемое время.

Эти три фактора делают проектирование аппаратного обеспечения похожим на написание компьютерных программ. Применение ЯОП и САПР позволяет проектировщику сконцентрироваться на основной задаче проектирования, в то время, как рутинная работа остаётся прерогативой компьютера.

Но все эти грандиозные достижения сми по себе не помогают создавать конкурентноспособные <<dd,цифровые устройства>>. Это возможно только при наличии проектировщика, который располагает хорошими знаниями принципов, лежащих в основе современных методов проектирования. Эти главные принципы включают, к примеру, метод микропрограммного управления и принцип представления цифрового устройства, как композицию операционного и управляющего автомата. Эти главные принципы разрабатывались как западными учёными (США, Западная Европа и Япония), так и восточными (страны бывшего СССР). Поскольку в прошлом компьютерные науки имели довольно военную направленность, footnote::[это же отразилось на развитии языков программирования] некоторые достижения западных учёных были неизвестными для из восточных коллег, и наоборот. Авторы в этой книге предприняли попытку собрать воедино методы западной и восточной ветви компьютерных наук.

В первой части книги, где изложена некоторая базовая информация, авторы пытаются устранить влияние технологий на методы проектирования <<clc,комбинационных>> и канонических схем <<fsm,конечных автоматов>>. Исходя из этого, все примеры в книге иллюстрированы применением базовых вентилей, таких как <<nand,НЕ-И>> и <<nor,НЕ-ИЛИ>>. Эта книга написана для читателей, знакомых с булевой алгеброй и главными принципами проектирования комбинационных схем. Её прочтение позволит облегчить решение задач минимизации булевых функций, реализации <<ff,триггеров>> и некоторых последовательных устройств, как счётчики и сдвиговые регистры. Есть ещё много хороших книг, которые детально обсуждают эти задачи.

Эта книга посвящена методам проектирования цифровых устройств, реализующих некоторые вычисления в определённых алгоритмах. Существуют два метода реализации таких устройств:

_Программная реализация_. В этом случае процесс проектирования сводится к написанию программы, для исполнения которой требуется лишь стандартное оборудование, такое как микропроцессор. Этот подход характеризуется низкой стоимостью реализации (положительная сторона) и очень низкой производительностью (отрицательная сторона). Такой подход используется, когда производительность микропроцессора удовлетворяет требованиям решаемой задачи.

_Аппаратная реализация_. В этом случае проектировщик подстраивает оборудование под исполнение определённого алгоритма или некоторого их набора. Таким оборудованием, как правило, являются интегральные схемы специального назначения (<<asic,ИССН>>). Это подход характеризуется высокой стоимостью разработки и оправдан лишь в том случае, когда производительность является главным критерием качества разрабатываемого проекта.

В этой книге рассматривается аппаратная реализация цифровых устройств, но рассматриваемые метода проектирования не относятся к определённой ИССН технологии. Первая часть книги посвящена проектированию тракта данных (или <<oa,операционного автомата>>). Эти устройства представляют кирпичики аппаратного проектирования. Один из результатов проектирование тракта данных - <<fc,блок-схема>>, используется для построения управляющего автомата (или <<cu,устройства управления>>).

Устройство управления - одна из важнейших частей любой цифровой системы; она отвечает за взаимодействие с другим компонентами системы. Как правило, устройства управления имеют нестандартную структуру, что делает проектирование их <<lc,логической схемы>> довольно нетривиальной задачей. Если речь идёт о сложных <<plc,логических контроллерах>>, то задача их проектирования сводится к проектированию устройств управления. На самом деле мы наблюдаем настоящий технический взрыв, связанный с достижениями в полупроводниковых технологиях. Одной из таких технологий является разработка интегральных микросхем <<sopc,ПЛИС>>, в которых количество элементов достигает миллиарда. По причине высокой сложности микросхем очень важно разрабатывать эффективные методы проектирования, ориентированные на определённые свойства логических элементов. Решив данную задачу можно улучшить функциональные возможности целевых цифровых систем, расположенной на одной ПЛИС микросхеме. Как отмечают большинство исследователей, используемые в промышленных масштабах для создания сложных цифровых систем методы проектирования далеки от совершенства. Это также касается проектирования устройств управления со стандартными <<fpld,ПЛИС>>: <<pla,ПЛМ>>, <<gal,ОЛМ>>, <<cpld,СПЛИС>> и <<fpga,ППВМ>>. Следует отметить, что современные <<sopc,системы на ПЛИС>> основаны на <<cpld,СПЛИС>> и <<fpga,ППВМ>> технологиях. поэтому разработка эффективных методов проектирования <<fpga,ППВМ>> остаётся задачей первостепенной важности.

Один из возможных путей оптимизации устройств управления (по критерию размера и производительности логической цепи) состоит в приспособлении их структуры к выполнению определённого <<ca,алгоритма управления>>. В данной книге алгоритмы управления изображаются в виде <<gsa,блок-схем>> с закодированной информацией о выполняемых операциях и проверяемых предикатах. Совершенно очевидно, что такое представление алгоритма очень просто и наглядно объясняет предлагаемые авторами методы. Авторы ограничиваются использованием линейных блок-схем. где блоки операторов составляют не менее 75% от общего количества блоков. Для реализации таких алгоритмов предлагаются композиционные микропрограммные устройства управления (<<cmcu,КМУУ>>), которые состоят из двух блоков: конечного автомата, который выполняет микропрограммные инструкции и памяти ля хранения микропрограммы. Большая часть книги посвящена проектированию и оптимизации характеристик <<cmcu,КМУУ>>.

Мы надеемся, что эта книга будет полезна студентам и аспирантам в сфере компьютерных наук.

[glossary]
== Глоссарий

Ниже приведён перечень терминов, которые встречаются в тексте.

[[sopc]]System on programmable chip (SoPC)::
    Система на программируемых логических интегральных схемах (<<fpld,ПЛИС>>).

[[ge]]Gate equivalent (GE)::
    Единица измерения сложности цифровых <<lc,логических схем>>.

[[hdl]]Hardware definition language (HDL)::
    Язык для описания поведения цифровых <<lc,логических схем>>.

[[cad]]Computer-aided design (CAD)::
    Система автоматизированного проектирования (САПР).

[[dd]]Digital device::
    Физическая единица оборудования, которая содержит в себе компьютер или микроконтроллер.

[[clc]]Combinational logic circuits::
    Комбинационные <<lc,логические схемы>>, где выходной сигнал полностью зависит от входного.

[[fsm]]Finite state machine::
    Конечный автомат - модель устройства с конечным числом состояний.

[[nand]]NAND logic gate::
    НЕ-И <<lg,вентиль>>, который работает, как конъюнктор с инвертором.

[[nor]]NOR logic gate::
    НЕ-ИЛИ <<lg,вентиль>>, который работает, как дизъюнктор с инвертором.

[[ff]]Flip-flop::
    Триггер - единица памяти, состоящая из двух <<nor,вентилей НЕ-ИЛИ>>.

[[asic]]Application-specific integrated circuit (ASIC)::
    Интегральная схема, специализированная для решения узкого круга задач.

[[oa]]Operational automaton::
    Часть микропроцессора, выполняющая обработку данных.

[[fc]]Flow-chart::
    Блок-схема - графическое представление алгоритма.

[[cu]]Control unit::
    Устройство управления - компонент микропроцессора, который направляет его работу.

[[lc]]Logic circuits::
    Схема из <<lg,логических вентилей>>.

[[lg]]Logic gate::
    Электронная схема, выполняющая логическую операцию.

[[plc]]Programmable logic controller::
    Программируемый логический контроллер - <<dd,цифровое электронная схема>>, контролирующая устройства ввода и принимающая решения по управлению выходными устройствами.

[[fpld]]Field-rogrammable logic device (FPLD)::
    Электронный компонент для создания конфигурируемых цифровых <<lc,логических схем>>.

[[pla]]Programmable logic array (PLA)::
    Программируемая логическая матрица (тоже, что <<pal,ПЛМ>>).

[[pal]]Programmable array logic (PAL)::
    Программируемая матрица логики (тоже, что <<pla,ПЛМ>>).

[[gal]]Generic array logic (GAL)::
    <<fpld,ПЛИС>> с программируемой матрицей И и фиксированной матрицей ИЛИ.

[[cpld]]Complex programmable logic device (CPLD)::
    Сложные <<fpld,ПЛИС>> с внутренней энергонезависимой памятью.

[[fpga]]Field-programmable gate array::
    Программируемая пользователем логическая матрица (ППВМ).

[[ca]]Control algorithm::
    Алгоритм управления - это логика обработки измеряемых данных для принятия решений.

[[gsa]]Graph-schemes of algorithms (GSA)::
    См. <<fc,Блок-схемы>> алгоритмов.

[[cmca]]Compositional microprogram contrrol units (CMCU)::
    Композиционные микропрограммные устройства управления.
