= Срочная ссуда

<<flashloan,Срочная ссуда>> cite:[flashloan] - это новый тип <<leading,беззалогового кредитования>>, который стал популярным благодаря протоколам децентрализованного финансирования (ДеФи), основанных на сети Эфириума.

Этот тип ссуд приобрёл популярность из-за взлома уязвимых протоколов децентрализованного финансирования, что привело к потере миллионов долларов. Ещё сторонники позиционирую срочную ссуду как инновационный и полезный инструмент в сфере финансов для арбитража и <<trade,быстрых сделок>>, которые стали возможным с появлением блокчейна.

Широко известны обычные ссуды. Заимодавец предоставляет деньги заёмщику, чтобы в конечном итоге они были полностью возвращены. Заимодавец получает от заёмщика вознаграждение за временное использование его денег.

Срочные ссуды похожи, но у них есть следующие уникальные свойства:

- Они используют <<smartcontract,умные контракты>> для отложенного запуска транзакций. Это инструмент блокчейна, который позволяет держать средства нетронутыми до выполнения определённого условия. В случае срочной ссуды таким условием является наступление времени, когда заёмщик должен вернуть средства заимодателю. В противном случае умный контракт сделает так, что займа и вовсе не было.
- Беззалоговый займ: часто заимодатели требуют от заёмщиков предоставить залог, чтобы гарантировать, что, если заёмщик не сможет погасить займ, заимодатель всё ещё сможет вернуть свои деньги. Но в беззалоговом займе залог не требуется. Отсутствие залога не означает, что заимодатель срочной ссуды не получит свои деньги обратно. Его просто отправляют обратно другим способом. Вместо того, чтобы предлагать залог, заёмщик должен немедленно вернуть деньги, что подводит нас к следующему пункту.
- Мгновенный: как правило, получение займа - это длительный процесс. Если заёмщик получает одобрение на получение займа, он или она, как правило, должны стабильно выплачивать его в течение нескольких месяцев или лет. Срочный кредит, однако, является мгновенным. Умный контракт по кредиту должен быть выполнен в той же транзакции, в которой он был выдан. Это означает, что заёмщик должен обратиться к другим умным контрактам для совершения мгновенных сделок с заёмным капиталом до завершения сделки, что обычно занимает несколько секунд. 

Этот тип займа может быть полезен в определённых случаях, например, для трейдеров, стремящихся быстро получить прибыль от арбитражных возможностей, когда два рынка по-разному оценивают криптовалюту. 

Платформа кредитования Ethereum Aave впервые выдвинула эту идею в начале 2020 года. Концепция новая и все ещё имеет много недоработок, потому что новые хаки делают это совершенно ясным. “Нет никакой реальной аналогии со срочными сделками", - говорится в документации платформы кредитования Ethereum Aave.

