[glossary]
== Глоссарий

[[st]]Single-threading::
    Однопоточность - последовательное выполнение инструкций.
[[mt]]Multi-threading::
    Многопоточность - одновременное выполнение нескольких последовательностей инструкций.
[[ts]]Thread-safety::
    Потокобезопасность - способность кода программы корректно работать при использовании его одновременно несколькими <<cf,потоками управления>>.
[[re]]Reentrancy::
    Реентерабельность - способность подпрограммы быть вызванной одновременно в разных <<cf,потоках управления>>.
[[cf]]Control-flow::
    Поток управления - последовательность передачи управления цифровым вычислительным устройством от одной инструкции к другой в пределах одного процесса.
[[lc]]Lock::
    Замок - механизм контроля доступа к данным с целью их защиты cite:[concurrency].
[[cfg]]Control-flow graph::
    Граф потока управления - множество всех возможных путей исполнения программы, представленное в виде графа.
[[algo]]Algorithm::
    Алгоритм - порядок действий для решения определённой задачи или правила решения класса задач.
[[cfi]]Control-flow integrity::
    Целостность потока управления - ограничение возможности выполнения программы в пределах заданного графа потока управления.
[[cg]]Call graph::
    Граф вызовов - ориентированный граф, где узлы соответствуют подпрограммам, а рёбра означают вызовы между подпрограммами.
[[ic]]Indirect call::
    Косвенный вызов - вызов процедуры, адрес которой находится в переменной.
[[ib]]Indirect branch::
    Косвенный переход - передача управления инструкции, находящейся по адресу, заданному в переменной.
[[cfa]]Control-flow analysis::
    Анализ потока управления - статический анализ кода с целью построения графа потока выполнения.
[[lb]]Local branch::
    Локальный переход - переход в пределах выполняемой подпрограммы.
[[fe]]Forward-edge::
    Прямой переход - переход к началу подпрограммы.
[[be]]Back-edge::
    Обратный переход - переход к инструкции, следующей за инструкцией вызова подпрограммы.
[[coro]]Coroutine::
    Сопрограмма - средство обеспечения многопоточности путём <<yield,переключения контекстов>> прикладной программой.
[[yield]]Context switch::
    Переключение контекста - сохранение состояния вычислителя в памяти и загрузка из памяти состояния вычислителя, сохранённого при выполнении другой задачи.
[[api]]Application programming interface::
    Интерфейс программирования приложений - набор сигнатур алгоритмов, выполняющих общую задачу, служащих одной цели или обрабатывающих одни и те же данные.
[[term]]Term::
    Термин - это слово или набор слов, которое имеет определённое значение в узкой предметной области.
[[reddit]]Reddit::
    Reddit - сайт, созданный Стивом Хоффманом в 2005 году для обсуждения материалов из сети Интернет.
[[http]]Hypertext transfer protocol::
    Протокол передачи гипертекста - сетевой протокол взаимодействия компьютеров с веб-сервером для предоставления гипертекстовой информации.
[[flashloan]]Flash loan::
    Срочная ссуда - предоставление денежных средств или имущества на заранее оговорённый срок cite:[ssudo].
[[lending]]Uncollateralized lending::
    Беззалоговое кредитование - это выдача кредита на основании платёжеспособности получателя и без поручительств и займов cite:[bezzal].
[[trade]]Quick trade::
    Быстрые сделки - это платформа для мгновенной конвертации криптовалют.
[[smartcontract]]Smart contract::
    Смарт-контракты - это инструмент для автоматического запуска транзакций при выполнении заданных условий без помощи посредников.
[[wallet]]Digital walet::
    Цифровой кошелёк - цифровое устройство, смарт-карта, или набор реквизитов для хранения и использования денежных средств.
[[castodial]]Castodial wallet::
    Кастодиальный кошелёк - это кошелёк, закрытый ключ которого хранится у третьей стороны.
[[dapp]]Decentralized application::
    Децентрализованное приложение - приложение с открытым исходным кодом, которое использует глобальную сеть компьютеров для координации взаимодействия и не контролируется одной сущностью.
[[dao]]Decentralized Autonomous Organization::
    Децентрализованная автономная организация - компания, не имеющая выделенного центра, которая управляется без участия человека.
[[defi]]Decentralized Finance::
    Децентрализованные финансовые сервисы - общедоступные финансовые инструменты с открытым исходным кодом, которые используют смарт-контракты.
[[blockchain]]Blockchain::
    Блокчейн - открытая распределённая база данных.
[[zeroproof]]Zero-knowledge proof::
    Доказательство с нулевым разглашением - криптографический метод доказательства того, что некоторая информация существует без разглашения этой информации.
[[sharding]]Sharding::
    Сегментирование базы данных - разделение базы данных на сегменты, каждый из которых управляется отдельным экземпляром сервера базы данных.
[[replication]]Replication::
    Репликация - копирование изменений из одной базы данных в другую.
[[lightning]]Lightning Network::
    Молниеносная сеть - технология проведения мгновенных транзакций в криптовалюте.
[[token]]Token::
    Токен - единица учёта инвестиций в проектах.
[[nft]]Non Fungible Token::
    Невзаимозаменяемый токен - криптографический токен, экземпляры которого уникальны.
[[ico]]Initial coin offering::
    Первичное размещение монет - форма привлечения инвестиций путём продажи инвесторам фиксированного количества новых единиц криптовалюты.
[[depth]]Depth of Market::
    Биржевой стакан - таблица цен и суммарного объёма заявок на бирже ценных бумаг.
[[consesus]]Consensus::
    Консенсус - метод принятия решений на основе общего согласия без голосования.
[[provider]]Liquidity provider::
    Маркетмейкер - лицо или организация, которая приобретает и удерживает на своём счёте ценные бумаги определённого эмитента с целью организации их продаж.
[[stock]]Stock exchange::
    Фондовая биржа - организация, которая обеспечивает обмен ценных бумаг: акций, облигаций, и других финансовых инструментов.

=== Интерфейсы подключения цифровых устройств

[[ide]]Integrated Drive Electronics, Parallel Advanced Technology Attachment::
    Привод встроенной электроники - интерфейс подключения накопителей с помощью 40-проводного кабеля, по которому за один раз передаётся 16 бит информации.


