Общие концепции программирования: написание и отладка программ
==============================================================
AT&T, Второе издание, 1999

== Написание реентерабельного и потокобезопасного кода

В <<st,однопоточных>> программах есть только один <<cf,поток управления>>. Так что код таких программ не обязан быть <<re,реентерабельным>> или <<ts.потокобезопасным>>. В <<mt,многопоточных>> программах несколько потоков управления могут одновременно выполнять одну и ту же подпрограмму и получать доступ к одним и тем же данным. Для защиты этих данных код многопоточной программы должен быть реентерабельным и потокобезопасным.

Глава повествует о написании реентерабельных и потокобезовасных программ. Она не освещает тему эффективности распараллеливания программ, это достигается лишь на этапе проектирования программы. Для того. чтобы распараллелить существующие однопоточные программы из нужно полностью препроектировать и переписать.

=== Определение реентерабельности и потокобезопасности




include::glossary.adoc[]
