Общие концепции программирования: написание и отладка программ
==============================================================
AT&T, Второе издание, 1999

Источник: https://web.archive.org/web/20060519053802/http://davinci01.man.ac.uk/aix433/aixprggd/genprogc/writing_reentrant_thread_safe_code.htm

== Написание реентерабельного и потокобезопасного кода

В <<st,однопоточных>> программах есть только один <<cf,поток управления>>. Так что код таких программ не обязан быть <<re,реентерабельным>> или <<ts.потокобезопасным>>. В <<mt,многопоточных>> программах несколько потоков управления могут одновременно выполнять одну и ту же подпрограмму и получать доступ к одним и тем же данным. Для защиты этих данных код многопоточной программы должен быть реентерабельным и потокобезопасным.

Глава повествует о написании реентерабельных и потокобезопасных программ. Она не освещает тему эффективности распараллеливания программ, это достигается лишь на этапе проектирования программы. Для того. чтобы распараллелить существующие однопоточные программы из нужно полностью перепроектировать и переписать.

=== Определение реентерабельности и потокобезопасности

И реентерабельность и потокобезопасность связаны со способом управления ресурсами функцией. Реентерабельность и потокобезопасность - это разные понятия: функция может быть либо реентерабельной, либо потокобезопасной, либо ни той, ни другой.

==== Реентерабельность




include::glossary.adoc[]
