= Времена

== Формы настоящего времени

=== Present Simple (PS)

Используется:

. для постоянных состояний, повторяющихся действий, повседневных задач;
. общеизвестные факты, законы природы;
. расписания (поездов, самолётов);
. спортивные комментарии, обзоры, рассказы;
. инструкции и наставления.

PS используется со следующими словами: usually (обычно), often (часто), always (всегда), каждый день, утром, вечером, в Понедельник.

=== Present Contiuous (PC)

Используется для:

. Действий, которые происходят сейчас. в момент говорения;
. временных действий, которые происходят почти сейчас, но не в момент говорения;
. действий, которые происходят очень часто, обычно выражая при этом недовольство;
. действий, которые запланированы на ближайшее назначенное время;
. развивающиеся или изменяющиеся ситуации.

=== Present Perfect (PP)

. Действия, которые начались в прошлом, и продолжаются до сих пор, особенно, с глаголами состояния иметь, быть, любить, знать. В таком случае применяется for или since.
. Действия, которые недавно завершились, и их результат виден в настоящий момент.
. Действия, которые произошли в неустановленное время в прошлом. Точное время неизвестно, или не имеет значения. Акцент делается на действии.
. Действия, которые произошли в определённый промежуток времени, не завершившийся к моменту говорения. Обычно используются слова сегодня, утром, вечером.

Примечание: PP используется для того, чтобы сообщить небольшую новость, а Past Simple и Past Continuous, чтобы рассказать подробнее про неё.

Past Perfect используется со следующими словами: for (на протяжении), since (с такого-то времени), уже, ещё, всегда, просто, даже, никогда, пока что, сегодня, на этой неделе, как долго, недавно, всё ещё.

=== Present Perfect Continuous (PPC)

Используется:

. Чтобы сделать акцент на продолжительности действия, которое началось в прошлом и продолжается до сих пор, особенно с временными выражениями вида for, since, весь день, целый год.
. Действия, которые началось в прошлом и продолжалось некоторое время. Действие могло завершиться или по-прежнему продолжается. Результат действия виден сейчас.
. Чтобы выразить возмущение, недовольство, раздражение.

Примечание: со словами жить, работать, учить, и чувствовать (некоторые эмоции) используется PP или PPC без разницы в смысле.

PPC используется со следующими временными выражениями: for, since, как долго, недавно.

Примечание: PP используется, чтобы сделать акцент на количестве, а PPC - на продолжительность.

== Наречия частоты

Наречия частоты (всегда, обычно, часто, иногда, редко, никогда) идут перед главным глаголом (читать, писать), но после глагола быть, и вспомогательных глаголов (di, have) или модальных глаголов (может, должен). Наречия частоты следуют перед вспомогательными глаголами в коротких вопросах.

Выражения вида каждый день, однажды/дважды в неделю/месяц, почти каждое утро/вечер находятся в самом начале или конце предложения. Обычно, часто, иногда, нормально, периодически могут находиться в начале или конце предложения для большей выразительности.

Наречия никогда и редко имеют негативный оттенок и не используются с частицей не.

== Глаголы состояния

Глаголы состояния, в отличие от обычных глаголов, выражают состояние а не действие. Поэтому, они не могут употребляться в продолжительной (continuous) форме. Это такие глаголы:

. Которые выражают предпочтения и неприязнь: нравится, любит, не нравится, обожает, предпочитает, восхищается;
. ощущения: видеть, слышать, нюхать, чувствовать вкус и запах, смотреть, слушать. Глагол могу используется с этими глаголами, когда они ссылаются на объект наблюдения или слушания в момент говорения;
. глаголы восприятия: знать, верить, понимать, осознавать, помнить, забыть, обратить внимание, узнать, считать что, казаться, видеть (в зн. понимать), ожидать;
. некоторые другие глаголы, такие как быть, содержать, включать, принадлежать, помещаться, нуждаться, стоить, иметь в виду, иметь вещь, иметь значение, быть должным (to owe), иметь (в зн. обладать), требовать, иметь вес (to weigh), желать, держать (в зн. сохранять).

Некоторые из вышеперечисленных глаголов используются в формах продолжительного времени, когда обозначают действия, а не состояния.

Примечания:

. Глагол наслаждаться можно использовать в продолжительной форме для того, чтобы выразить особые предпочтения.
. Глаголы видеть (ссылаясь на появление человека), чувствовать (выражая определённую эмоцию), ранить (hurt), болеть (ache) можно использовать как в простых, так и в продолжительных формах без разницы в значении.

== Have gone (to) / Have been (to)

Has gone (to) = ушла/ушёл (в). Используется, когда человек ещё не вернулся.

Has been (to) = была/был (у). Используется, когда человек уже вернулся.

Примечания: в этом случае been используется, как причастие прошедшего времени от глагола to go.

== Формы прошедшего времени

=== Past Simple

Используется:

. Для действий, которые произошли в определённое время в прошлом. Время установлено, уже известно или подразумевается.
. Для действия, которое произошло сразу после другого действия в прошлом.
. Привычки в прошлом, или состояния, которых уже нет. В таком случае мы используем конструкцию used to.

PS используется со следующими выражениями времени: вчера, следом, когда, как давно? Прошлой осенью, на той неделе, тому назад, в 1997 году.

=== Past Continuous

Используется:

. Для действий, которые развивались в установленное время в прошлом. Не указывается, когда действие началось, и когда закончилось.
. Для действия, которое развивалось, когда другое действие прервало его. При этом PC используется для действия, которое развивалось (длительное действие); и PS для действия, что прервало его (короткое действие).
. для двух и более одновременных действий.
. для описания атмосферы, окружения, в предисловии к истории, перед рассказом основных событий.

PC используется со следующими временными выражениями: пока, когда, как, всё утро/вечер/день/ночь.

=== Past Perfect

Используется для:

. Действия, которое произошло до другого действия в прошлом, или установленного времени в прошлом.
. Действия, которое завершилось в прошлом, и его результата тоже виден в прошлом.

Примечание: PP есть эквивалент настоящего PP для прошедшего времени.

PP используется со следующими выражениями времени: до, после, уже, просто. For, since, до тех пор, пока, когда, около, к тому времени.

Примечание: PP и PS используется со словами до и после без разницы в смысле.

=== Past Perfect Continuous

Используется:

. Чтобы сделать акцент на продолжительности действия, которое началось и закончилось в прошлом перед другим прошедшим действием или установленным временем в прошлом, обычно со словом since и for.
. Для действия, которое продолжалось когда-то в прошлом, и его результат виден в прошлом.

Примечания: PPC есть эквивалент настоящего PPC для прошедшего времени.

PPC используются со следующими временными выражениями: for, since, как долго, до, доколе.

== Конструкция Used To / Would

Конструкция #Used to + инфинитив# используется для выражения привычек в прошлом или состояний. В таком случае used to можно заменить на past simple без изменения смысла.

Used to не заменяет Past simple в следующих случаях:

- Действие, произошедшее в заданное время в прошлом;
- чтобы указать, как часто происходило действие в заданное время в прошлом.

Would/used to используется для повторяющихся действий или расписаний в прошлом.

Be used to + существительное/местоимение/ing-форма = привыкайте к, в привычке.

Get used to + существительное/местоимение/ing-форма = привыкли к.

=== Past Simple

Простое прошедшее время используется для действий, произошедших в прошлом, не связанных с настоящим.

- Действия, произошедшие в определённое время в прошлом; время начала уше известно, или подразумевается.
- Действия, которые начались и закончились в прошлом.
- Действия в прошлом, которые не могут повторяться.
- Действия, совершившееся в период времени, который завершился.

Следует отметить, что простое прошедшее время используется для действий человека, которого нет в живых, даже если время е установлено.

=== Past Perfect

Прошедшее завершённое время используется для действий, совершённых в прошлом, связанных с настоящим.

- Действия, совершённые в неустановленное время в прошлом; время неизвестно, или не существенно, поэтому не указывается и не предполагается.
- Действия, которые начались в прошлом и продолжаются до сих пор.
- Действия, осуществлённые в прошлом, и которые могут повторяться.
- Действия, совершившееся в период времени, который ещё не завершился.

== Past Simple / Past Continuous / Past Perfect

Простое прошедшее время используют для действий, которые совершались один за другим в прошлом.

Прошедшее продолжительное время используется для продолжительного действия, которое осуществлялось в прошлом, когда другое действе прервало его.

Прошедшее завершённое время используется для действий, которое завершилось к моменту, когда началось другое действие.

Можно использовать все три формы прошедшего времени без разницы в значении со словами думал, ожидал, надеялся, предполагал, когда речь идёт о не совершившемся действии.

== Формы будущего времени

=== Простое будущее время

- Предположения о будущих событиях, обычно со словами считаю, думаю, верю, ожидаю; с выражениями боюсь, уверен. Прилагательные: вероятно, возможно, конечно.
- Спонтанные решения;
- обещания (со словами обещаю, гарантирую), угрозы, предупреждения, просьбы, надежды (со словом надеюсь), предложения;
- действия, события, ситуации, которые обязательно произойдут в будующем, и от нас это не зависит.

=== Be going to

- Планы, намерения, амбиции на будущее;
- действия, которые запланированы на ближайшее будущее;
- предсказания, основанные на фактах.

Заметьте, что:

1. Going to обычно означает, что мы что-то собирается сделать, а will - чтобы сообщить подробности или сделать комментарий;
2. вместо guild to обычно используется настоящее продолжительное время со словами, которые выражают движение, в частности, слова идти (go) и прийти (come).

Простое будущее время и going to используются со следующими словами и выражениями: завтра, послезавтра, ночью, скоро, на следующей неделе, на этой неделе, за 3 дня.

=== Будущее продолжительное время

- Длительное будущее действие, происходящее в определённое время;
- действие, которое обязательно произойдёт в будущем в результате распорядка или предписания;
- вежливый вопрос о предстоящих планах (когда пытаетесь узнать, что ваши желания отвечают их планам).

=== Будущее законченное время

Действия, которые должны завершиться к определённому моменту в будущем.

Будущее завершённое время используется со словами до, к моменту, перед тем, как.

Примечание: until/till используются в отрицательных предложениях.

=== Будущее продолжительно завершённое время

Делает акцент на продолжительности действия, которое завершится к определённому моменту в будущем.

Используется с by..for.

Примечание: осле выражений by the time, until, before используется простое настоящее время, поскольку они вводят время. Будущее продолжительное или завершённое время может следовать как до так, и после временных выражений.

Примечательно, что простое будущее время и продолжительное и законченное, все используются для предположения о настоящем или прошлом. Иными словами -- предполагаете, что что-то может произойти, или уже произошло.

=== Простое настоящее время

Простое настоящее время используется для будущих событий когда есть расписание, программа.

=== Настоящее продолжительное время

Настоящее продолжительное время используется для событий, которые запланированы на ближайшее будущее.

Простое настоящее и настоящее продолжительное время используется вместо будущего времени после слов _пока, до, после, до тех пор, пока, как, пока не, каждый раз, когда, если, предположим, однажды, единожды, как только, настолько долго, ко времени, в случае, при условии_, пр. 

Будущее время используется:

- с when когда оно используется, как вопросительное слово. Когда оно используется для обозначения времени, используется простое настоящее время.
- с if/whether, когда оно используется после выражений незнания, непонимания. Со словами я не знаю, я удивлён, я поражён, сомневаюсь.

== Простое будущее время против Be going to

Простое будущее время используется:

- когда делается предположение основанное на том, что вы думаете, полагаете, представляете.
- решения принятие на месте.

Going to используется:

- когда делается предсказание, основанное на том, что мы можем видеть (доказательства), или о чём известно;
- действия, которые уже запланированы на будущее.

== Will/Won't - Shall

Will you...? Означает просьбу или приказ.

Won't выражает нежелание, решительный отказ, даже если субъектом выступает не личность.

Wouldn't обозначает прошедшее время.

Shall I/we...? Используется:

- чтобы сделать предложение;
- чтобы дать совет;
- чтобы спросить совета или инструкций.

== Другие способы выражения будущего времени

- be to \+ инфинитив (формальный язык);
- be about to \+ инфинитив / be on the point of \+ -ing (недалёкое будущее) например: Автобус вот-вот отъедет. Предприятие находится на грани закрытия.
- be due to \+ инфинитив (расписания);
- глаголы решить, планировать, намереваться, собираться, хотеть \+ инфинитив (планы и намерения);
- be sure to / be certain to / be bound to \+ инфинитив (выражает уверенность в будущих событиях), например: план обязательно осуществится.

[align=center]
Будущее в прошедшем времени

Следующие образцы используются для того, чтобы сказать что вы намеревались делать.

- was guing to / was to / was about to / was due to \+ инфинитив.
- wason the point of \+ -ing форма.

== Иными словами (примеры)

Впервые слышу настолько грустную историю. - Это грустнейшая история, которую я когда-либо слышал.

Он начал рисовать 15 лет назад. - Он рисует уже 15 лет.

Она ещё не закончила украшение квартиры. - Она всё ещё украшает квартиру.

Я до этого не вкушал китайской пищи. - Это первый случай, когда я ем китайскую еду.

Когда они окончили колледж? - Сколько времени прошло с тех пор, как они окончили колледж? - Как давно они окончили колледж?

Он не начнёт говорить, пока все не присядут. - Он ждёт, чтобы все сели, прежде чем начнёт говорить.

Мы не были в театре целый год. - Последний раз мы ходили в театр год назад.

Прошло два года после отпуска. - Не было отпуска два года.

Впервые путешествую на лодке. - Никогда ранее не путешествовал на лодке.

Джек собирался ужинать, когда ему позвонил босс. - Джек уже начинал ужинать, когда ему позвонил босс.

== Распространённые ошибки

Я позвоню, *когда [.line-through]#буду# закончу*.

Я *[.line-through]##до##читал* эту книгу месяц назад.

Я встретил его *[.line-through]#два дня# прежде*.

Возьми карту *на случай, если [.line-through]#будешь# потеряешься*.

Когда ты *последний раз ходил [.line-through]#был#* в кино?

Я не видел его *с тех пор, как окончил* школу.

*Учу* английский *с 1996 года*.

Он *бросил* курить *год назад* [.line-through]#перед#.

Шарон нашла работу месяц назад. Она *бросила* школу под года *назад*.

Они всё ещё *не* позвонили нам.

Он *всё ещё не приобрёл* компьютер.

Она *ещё* за границей.

Они *ещё не пришли* к решению.

Они *должны вернуться к* [.line-through]#до#  полудню.

*Ходил* в кино *дважды в прошлом месяце*.

== Фразовые глаголы

be after::
    1) хотеть, пытаться завоевать; 2) преследовать.

be against::
    противопоставлять (обратно *be for*).

be in for::
    ожидать чего-либо (нехорошего).

be off::
    1) не хотеть/желать более; 2) отсутствовать (в школе, на работе).

be on::
    сниматься (в кино, по телевизору).

be out of::
    не иметь чего-либо, недоставать.

be over::
    пришел конец.

be up::
    1) проснуться и встать; 2) не спать ночью; 3) быть странным или плохим.

break down::
    1) прекратить работу; 2) потерять контроль над чувствами; 3) провалиться.

break in / break into::
    1) экстренно войти; 2) прервать.

break out::
    1) внезапно начать (стрельбу, войну); 2) сбежать.

break up::
    1) прерваться на каникулы; 2) разделить, отделить.

