= Пассивный залог

Запретный город расположен в центре Пекина. Его построили, как императорский дворец для правителей Китая. Его назвали запретным по причине того, что никто не может попасть внутрь без разрешения.

Пассивный залог образуется глаголом to be и причастием прошедшего времени от смыслового глагола.

Настоящее/прошлое/будущее продолжительное завершённое время и продолжительное будущее время не используются в пассивном залоге.

Можно использовать глагол to get вместо to be в разговорной речи при изъяснении обстоятельств происшествия или неожиданности.

== Использование

- Когда субъект действия неизвестен, несущественен либо очевиден из контекста.
- Когда само действие важнее субъекта, как в заголовках новостей, формальных уведомлениях, инструкциях, рекламных объявлениях, описании технологического процесса.
- Когда речь идёт о неприятном событии, и вы не хотите выдавать того кто это сделал.

== Переход от активного к пассивному залогу

Что поменять активный залог на пассивный, в предложении нужно:

. объект из активного залога становится субъектом в пассивом залоге;
. глагол активного залога остаётся в том же времени, но в пассивной форме;
. субъект из активного залога становится агентом в пассивном залоге и вводится через предлог by либо опускается.

Только транзитивные глаголы (такие, за которым следует объект) могут быть представлены в пассивном залоге.
Некоторые транзитивные глаголы, такие как have, fit (поместиться), suit (подходить), resemble (походить) не имеют пассивной формы.

Конструкция be + агент используется, чтобы показать, кто совершает действие. Конструкция with + инструмент/материал/ингредиент для того, что использует агент.

Агент обычно не указывается в пассивном предложении, если субъект активного предложения представлен словом people, one, someone (некто), they, he, пр.
Агент не опускается, когда им является важное лицо или является сутью предложения.

Местоимения объекта (мне, тебе, ему) становятся местоимениями субъекта в пассиве.

С глаголами, которые имеют два объекта, такие как приносить, рассказать, послать, показать, научить, предложить, обещать, купить, бросить, написать, наградить, передать, продать, задолжать (owe), подарить, позволить, кормить, сдать, отправить, прочитать, брать, дать, заплатить, одолжить. Можно образовать два разных предложения в пассивной форме.

Если после глагола в активной форме следует предлог, то он сохраняется в пассивной форме.

Когда нужно узнать, кто или что совершает действие, задают вопрос вида Who/What..by?

После глаголов услышать, помочь, увидеть, осуществить следует инфинитив без частицы to. А в пассивной форме следует инфинитив с частицей to.
Но hear, see, watch + -ing как в активном так и в пассивном.

== Личные и безличные конструкции

Глаголы думать, верить, говорить, докладывать, знать, ожидать, используются в следующих образцах в дичной и безличной конструкциях.

Например: люди считают, что он солгал. (believe).

Пассивный залог (безличная форма): считают, что солгал. (It is believed).

Личная форма: На него считают, что он солгал. (He is believed to have lieed).

Активная форма: Они ожидают, что он скоро прибудет. (expect).

Пассивная безличная форма: Ожидается, что он скоро прибудет. (It is expected).

Личная форма: He is expected to arrive soon.

== Сделайте что-нибудь (have something done)

Simon is having his temperature taken. (His mother is taking his temperature).

Конструкция have + объект + причастие прошедшего времени используется для того, чтобы сказать, что мы попросили кого-то сделать  что-то для себя. Например: у нас были новые шкафы сделанные плотником. (Мы не делаем шкафы, а плотник их делает для нам).

Вопросы и отрицания для глагола have формируются с помощью do/does или did.

Have somethind done также использутеся для того, ятобы сказать, что нечто неприятное с кем-то произошло.

Глагол get можно использовать вместо have только в неформальной беседе.

== Иными словами (примеры)

Известно, что взрыв наносит значительный ущерб строениям. - Взрывы известны, как наносящие значительный ущерб строениям.

Братья Люмьер изобрели первую съёмочную станцию. - Первая съёмочная станция была изобретена братьями Люмьер.

Боб не любит, когда у него спрашивают о его работе. - Боб не любит быть озадаченным вопросом о его работе.

Они наняли знаменитого архитектора, чтобы он спроектировал им дом. - Их дом будет спроектирован знаменитым архитектором.

Некто угнал его мотоцикл, когда он был в банке. - Его мотоцикл был угнан, когда он был в банке.

Они накажут, если если будете продолжать причинять неприятности. - Будете наказаны, если продолжите причинять неприятности.

== Распространённые ошибки

Ксерокс недавно обслуживался.

Стив походит на знаменитого телеведущего.

Омлет изготовлен из яиц и сыра.

Кем был нарисован этот портрет?

Женщина услышала крик.

Говорят, он украл немного денег.

Как часто разукрашивают ваш дом?
