= Синтез операционных и управляющих автоматов

== Введение

Последние шестьдесят лет отмечены быстрым развитием компьютерных наук cite:[barkalov]. Ключевые особенности промышленности в данной области на сегодняшний день следующие:

. Разработка сверхсложных сверхбольших интегральных схем, таких, как программируемые чипы <<sopc,(ПЛИС)>>, где около млрд логических <<ge,вентилей>>. Современная микроэлектроника становится, если не наноэлектроникой, то где-то в этом роде, учитывая уменьшающиеся размеры как транзисторов так и проводников.
. Разработка языков описания аппаратуры <<hdl,(ЯОП)>>, таких как VHDL и Verilog, позволяющих охватить чрезвычайно сложные проекты.
. Повсеместное применение систем автоматизированного проектирования <<cad,(САПР)>> для создания сложных проектов за приемлемое время.

Эти три фактора делают проектирование аппаратного обеспечения похожим на написание компьютерных программ. Применение ЯОП и САПР позволяет проектировщику сконцентрироваться на основной задаче проектирования, в то время, как рутинная работа остаётся прерогативой компьютера.

Но все эти грандиозные достижения сми по себе не помогают создавать конкурентноспособные <<dd,цифровые устройства>>. Это возможно только при наличии проектировщика, который располагает хорошими знаниями принципов, лежащих в основе современных методов проектирования. Эти главные принципы включают, к примеру, метод микропрограммного управления и принцип представления цифрового устройства, как композицию операционного и управляющего автомата. Эти главные принципы разрабатывались как западными учёными (США, Западная Европа и Япония), так и восточными (страны бывшего СССР). Поскольку в прошлом компьютерные науки имели довольно военную направленность, footnote::[это же отразилось на развитии языков программирования] некоторые достижения западных учёных были неизвестными для из восточных коллег, и наоборот. Авторы в этой книге предприняли попытку собрать воедино методы западной и восточной ветви компьютерных наук.

В первой части книги, где изложена некоторая базовая информация, авторы пытаются устранить влияние технологий на методы проектирования <<clc,комбинационных>> и канонических схем <<fsm,конечных автоматов>>. Исходя из этого, все примеры в книге иллюстрированы применением базовых вентилей, таких как <<nand,НЕ-И>> и <<nor,НЕ-ИЛИ>>. Эта книга написана для читателей, знакомых с булевой алгеброй и главными принципами проектирования комбинационных схем. Её прочтение позволит облегчить решение задач минимизации булевых функций, реализации <<ff,триггеров>> и некоторых последовательных устройств, как счётчики и сдвиговые регистры. Есть ещё много хороших книг, которые детально обсуждают эти задачи.

Эта книга посвящена методам проектирования цифровых устройств, реализующих некоторые вычисления в определённых алгоритмах. Существуют два метода реализации таких устройств:

_Программная реализация_. В этом случае процесс проектирования сводится к написанию программы, для исполнения которой требуется лишь стандартное оборудование, такое как микропроцессор. Этот подход характеризуется низкой стоимостью реализации (положительная сторона) и очень низкой производительностью (отрицательная сторона). Такой подход используется, когда производительность микропроцессора удовлетворяет требованиям решаемой задачи.

_Аппаратная реализация_. В этом случае проектировщик подстраивает оборудование под исполнение определённого алгоритма или некоторого их набора. Таким оборудованием, как правило, являются интегральные схемы специального назначения (<<asic,ИССН>>). Это подход характеризуется высокой стоимостью разработки и оправдан лишь в том случае, когда производительность является главным критерием качества разрабатываемого проекта.

В этой книге рассматривается аппаратная реализация цифровых устройств, но рассматриваемые метода проектирования не относятся к определённой ИССН технологии. Первая часть книги посвящена проектированию тракта данных (или <<oa,операционного автомата>>). Эти устройства представляют кирпичики аппаратного проектирования. Один из результатов проектирование тракта данных - <<fc,блок-схема>>, используется для построения управляющего автомата (или <<cu,устройства управления>>).

