[glossary]
== Глоссарий

Ниже приведён перечень терминов, которые встречаются в тексте.

[[sopc]]System on programmable chip (SoPC)::
    Система на программируемых логических интегральных схемах (<<fpld,ПЛИС>>).
[[ge]]Gate equivalent (GE)::
    Единица измерения сложности цифровых <<lc,логических схем>>.
[[hdl]]Hardware definition language (HDL)::
    Язык для описания поведения цифровых <<lc,логических схем>>.
[[cad]]Computer-aided design (CAD)::
    Система автоматизированного проектирования (САПР).
[[dd]]Digital device::
    Физическая единица оборудования, которая содержит в себе компьютер или микроконтроллер.
[[clc]]Combinational logic circuits::
    Комбинационные <<lc,логические схемы>>, где выходной сигнал полностью зависит от входного.
[[fsm]]Finite state machine::
    Конечный автомат - модель устройства с конечным числом состояний.
[[nand]]NAND logic gate::
    НЕ-И <<lg,вентиль>>, который работает, как конъюнктор с инвертором.
[[nor]]NOR logic gate::
    НЕ-ИЛИ <<lg,вентиль>>, который работает, как дизъюнктор с инвертором.
[[ff]]Flip-flop::
    Триггер - единица памяти, состоящая из двух <<nor,вентилей НЕ-ИЛИ>>.
[[asic]]Application-specific integrated circuit (ASIC)::
    Интегральная схема, специализированная для решения узкого круга задач.
[[oa]]Operational automaton::
    Часть микропроцессора, выполняющая обработку данных.
[[fc]]Flow-chart::
    Блок-схема - графическое представление алгоритма.
[[cu]]Control unit::
    Устройство управления - компонент микропроцессора, который направляет его работу.
[[lc]]Logic circuits::
    Схема из <<lg,логических вентилей>>.
[[lg]]Logic gate::
    Электронная схема, выполняющая логическую операцию.
[[plc]]Programmable logic controller::
    Программируемый логический контроллер - <<dd,цифровое электронная схема>>, контролирующая устройства ввода и принимающая решения по управлению выходными устройствами.
[[fpld]]Field-rogrammable logic device (FPLD)::
    Электронный компонент для создания конфигурируемых цифровых <<lc,логических схем>>.
[[pla]]Programmable logic array (PLA)::
    Программируемая логическая матрица (тоже, что <<pal,ПЛМ>>).
[[pal]]Programmable array logic (PAL)::
    Программируемая матрица логики (тоже, что <<pla,ПЛМ>>).
[[gal]]Generic array logic (GAL)::
    <<fpld,ПЛИС>> с программируемой матрицей И и фиксированной матрицей ИЛИ.
[[cpld]]Complex programmable logic device (CPLD)::
    Сложные <<fpld,ПЛИС>> с внутренней энергонезависимой памятью.
[[fpga]]Field-programmable gate array::
    Программируемая пользователем логическая матрица (ППВМ).
[[ca]]Control algorithm::
    Алгоритм управления - это логика обработки измеряемых данных для принятия решений.
[[gsa]]Graph-schemes of algorithms (GSA)::
    См. <<fc,Блок-схемы>> алгоритмов.
[[cmcu]]Compositional microprogram contrrol units (CMCU)::
    Композиционные микропрограммные устройства управления.

